# name: Docs
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Python 3.x
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.9'

#       - name: Build Docs
#         run: |
#           pip install mkdocs mkdocs-mermaid2-plugin
#           mkdocs build




name: Docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false 

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build
        run: |
          pip install mkdocs mkdocs-mermaid2-plugin
          mkdocs build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site